apiVersion: apps/v1
kind: Deployment
metadata:
  name: forlink-member-deployment
  labels:
    app: forlink-member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forlink-member
  template:
    metadata:
      labels:
        app: forlink-member
    spec:
      containers:
        - name: forlink-member
          image: forlink-member:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 10001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
