apiVersion: v1
kind: Service
metadata:
  name: forlink-member-service
spec:
  selector:
    app: forlink-member
  type: NodePort
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30001